### ISSUE TITLE
Host site through github pages

### ISSUE THREAD

**Issue by ibab** [pep-dortmund/toolbox.pep-dortmund.de#10]

**Comment by itoijala** [comment]
@ibab could you enable Travis to see if this is working?

I think it should now be ready to go.

We should first test it before switching the DNS.

**Comment by ibab** [comment]
Travis has already been travising for some time: https://travis-ci.org/pep-dortmund/toolbox.pep-dortmund.de/builds

The problem is that pandoc doesn't build properly.
Will look into this.

**Comment by ibab** [comment]
It works!
http://pep-dortmund.github.io/toolbox.pep-dortmund.de

Whenever we update `site.hs`, we will have to commit the `site` binary to the `hakyll-bin` branch.
The old binary can be thrown away.

The `site` binary doesn't depend on any weird dynamic libraries, so it doesn't really matter on which system it is compiled.

**Comment by itoijala** [comment]
Done.
