### ISSUE TITLE
Ugly font in lead div

### ISSUE THREAD

**Issue by MaxNoe** [pep-dortmund/toolbox.pep-dortmund.de#11]
This looks really ugly:

![toolbox-lead](https://cloud.githubusercontent.com/assets/5488440/8606637/3c4dd8ee-268d-11e5-87ef-43a49626d276.png)

**Comment by ibab** [comment]
Is this on Windows or Linux?
Looks fine on my laptop:

---

![screen](https://cloud.githubusercontent.com/assets/890531/8606746/342c3074-268e-11e5-87e1-e2d527a546ce.png)

---

Can you find out which font is being used on your PC?

**Comment by MaxNoe** [comment]
Windows, on my arch it looks fine.

**Comment by MaxNoe** [comment]
Helvetica Neue, which is the rest of the font. But weight 200 is used, this is far to light.

**Comment by ibab** [comment]
Do you also see it [in the bootstrap documentation](http://getbootstrap.com/css/#lead-body-copy)?

**Comment by MaxNoe** [comment]
Yes, 300 looks fine.

**Comment by ibab** [comment]
Then I will simply update to the newest version.

**Comment by ibab** [comment]
Updating bootstrap breaks the navbar, unfortunately.

**Comment by MaxNoe** [comment]
then just change the 200 to a 300

**Comment by MaxNoe** [comment]
Just did it in  d621deba3cebe5d3b

**Comment by ibab** [comment]
>.< 
I was working on updating it properly.

**Comment by MaxNoe** [comment]
Sorry :D

**Comment by ibab** [comment]
Okay, bootstrap was used incorrectly in a few places.
I've updated bootstrap and fixed the HTML.
Does it look better on Windows now?

**Comment by MaxNoe** [comment]
Yes, much better
