### ISSUE TITLE
Installationsanleitung Todo

### ISSUE THREAD

**Issue by itoijala** [pep-dortmund/toolbox.pep-dortmund.de#14]
- Mac: Atom
- Linux: Atom?

**Comment by MaxNoe** [comment]
Arch: Paketete weglassen?

**Comment by itoijala** [comment]
> Arch: Paketete weglassen?

Ja, wir können die Arch-spezifischen Teile weglassen.
Natürlich nicht die mit git und make und so.

**Comment by itoijala** [comment]
Wie wollen wir Atom unter Linux installieren lassen.

Ich finde es unglaublich hässlich, ein .rpm oder .deb manuell reinzuladen.
Das wird doch dann niemals ein Update bekommen, dann benutzen Leute in 2 Jahren immer noch Version 1.0……
Unter Windows/Mac dürfte es ein Autoupdate geben.

**Comment by MaxNoe** [comment]
Zumindest bei Arch is es im AUR

**Comment by MaxNoe** [comment]
Und bei Ubuntu gibt es auch ein ppa: https://codeforgeek.com/2014/09/install-atom-editor-ubuntu-14-04/

**Comment by itoijala** [comment]
Wir unterstützen mindestens Debian, Ubuntu, Mint, Fedora, OpenSUSE und Arch.
Zumindest laut jetziger Anleitung.

**Comment by MaxNoe** [comment]
Ist vielleicht ein wenig über. Sind eh > 80% Windows

**Comment by itoijala** [comment]
Ich finde schon, dass wir die gängigen Distributionen unterstützen sollten.

**Comment by itoijala** [comment]
Git for Windows 2.5.0 wurde offiziell veröffentlicht und ist auf der Git-Seite verlinkt.

**Comment by MaxNoe** [comment]
Direktlinks zu den Anaconda-Versionen gibt es hier:
https://repo.continuum.io/archive/index.html

Zum Beispiel Windows, 64-bit, python3:
https://repo.continuum.io/archive/Anaconda3-2.3.0-Windows-x86_64.exe

**Comment by itoijala** [comment]
Ok, die werden schon (mit ein wenig Hilfe) verstehen, welche Datei sie holen sollen.

**Comment by itoijala** [comment]
Welche Versionen von make und git kriegt man eigentlich unter Mac?

**Comment by kdungs** [comment]
Die Standardversionen des Betriebssystems (10.10.4) sind:

```
% make --version
GNU Make 3.81

% /usr/bin/git --version
git version 2.3.2 (Apple Git-55)
```

Mit MacPorts kriegt man

```
% git --version
git version 2.5.0
```

Cheers,
Kevin

**Comment by kdungs** [comment]
Die Standardversionen des Betriebssystems (10.10.4) sind:

```
% make --version
GNU Make 3.81

% /usr/bin/git --version
git version 2.3.2 (Apple Git-55)
```

Mit MacPorts kriegt man

```
% git --version
git version 2.5.0
```

**Comment by itoijala** [comment]
Diese Apple-Leute, die meinen, sie könnten nicht das GPL3-Make nehmen……

Ich fänd's fast sinnvoller, git und make von MacPorts oder Homebrew zu nehmen…

Msys2 ist leider auf SourceForge gehostet…… hab eine Warnung in die Anleitung geschrieben.

**Comment by itoijala** [comment]
Mac, Linux: Atom

Bump

**Comment by MaxNoe** [comment]
Dumme Frage, aber wenn wir auf windows msys2 installieren lassen, warum dann nicht pacman -S git?

**Comment by itoijala** [comment]
Gute Frage…

Ist das `git` das gleiche was man mit git-for-windows bekommt?
Ich guck mal.

**Comment by MaxNoe** [comment]
Letzter commit hier: https://github.com/Alexpux/MSYS2-packages ist `git: Update to 2.5.2`

**Comment by itoijala** [comment]
Die nehmen aber direkt den Code von Standard-`git`, heißt ohne die Verbesserungen von git-for-windows.

**Comment by itoijala** [comment]
Die Links zu Anaconda sollten angepasst werden.
Die Seite wurde umgebaut, jetzt ist Py3 direkt sichtbar und wir brauchen nicht auf die unübersichtliche Archivliste verlinken.

**Comment by itoijala** [comment]
Anaconda-Links sind angepasst.

Bei Atom für Mac nicht vergessen, den auch als Editor für Git einzustellen (siehe Windows-Teil).
