### ISSUE TITLE
Image 'img/texlive-3.png' is missing

### ISSUE THREAD

**Issue by LuckyJosh** [pep-dortmund/toolbox.pep-dortmund.de#18]
The image to be displayed beneath the line

> Wir brauchen TeXworks nicht:

is missing.

**Comment by LuckyJosh** [comment]
Actually it is not the third image that is missing but the first.
The line above the first image does not fit the content of the image.
I'm going to add the missing image

**Comment by mennthor** [comment]
Where exactly is this missing? 🙈

**Comment by LuckyJosh** [comment]
In the "install TeXLive on windows" section.
