### ISSUE TITLE
List of editors.

### ISSUE THREAD

**Issue by kdungs** [pep-dortmund/toolbox.pep-dortmund.de#9]
http://toolbox.pep-dortmund.org/links.html#editoren
List of editors features (only!) emacs?

**Comment by bixel** [comment]
Fixed, did you notice the emacs link?

**Comment by MaxNoe** [comment]
That's a serious defect

**Comment by bixel** [comment]
What's the problem? I think the site gets the markdown from this repo. The `links.md` is fixed, but the website does'nt show the updates.

**Comment by ibab** [comment]
You should reference the fixed issue from your commit, so other people can see that it's been fixed.
I've suspended the automatic deployment at some point this year.
Maybe we should switch to deploying with travis?

**Comment by itoijala** [comment]
Maybe we should switch to a hosting provider with a bus factor > 1, especially since it will soon be an English bus……

We only need static files, so that shouldn't be so hard. Deployment could just be "compile locally and ftp it up".

**Comment by ibab** [comment]
But then someone needs to host the static files.
We can compile the site with travis and push to `gh-pages`, like I've done here: https://github.com/lhcb/first-analysis-steps/blob/master/.travis.yml

**Comment by itoijala** [comment]
`gh-pages` seems pretty much optimal.

**Comment by kdungs** [comment]
Damnit, Ismo it took me a while to get your "bus" joke...

I am also much in favour of using `gh-pages`. See #10 for further discussion.

**Comment by itoijala** [comment]
We decided to just use Atom. *sigh*
